# -*- mode: ruby -*-
# vi: set ft=ruby :

# Provide docker engine for Windows.

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"
  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 4
  end

  config.vm.network "private_network", ip: "192.168.56.201"

  config.vm.provision "shell", inline: <<-SHELL
    curl -sSL https://get.docker.com/ | sh
    sudo usermod -aG docker vagrant
    sudo systemctl start docker.service
    echo docker service successfully started.
  SHELL
end
